# Generated by Django 2.1.4 on 2018-12-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='academic_level',
            field=models.CharField(choices=[('ninguna', 'ninguna'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Tecnico', 'Tecnico'), ('Profesional', 'Profesional')], default='ninguna', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(default='Ninguno', max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='skill',
            field=models.CharField(choices=[('ninguna', 'Ninguno'), ('Empatia', 'Empatia'), ('Sociabilidad', 'Sociabilidad'), ('Facilidad de Comunicación', 'Facilidad de Comunicación'), ('Escucha activa', 'Escucha activa'), ('Trabajo en equipo', 'Trabajo en equipo'), ('Adaptación al cambio', 'Adaptación al cambio'), ('Creatividad', 'Creatividad'), ('Capacidad para resolver problemas', 'Capacidad para resolver problemas'), ('Optimización del tiempo', 'Optimización del tiempo'), ('Actitud Positiva', 'Actitud Positiva'), ('Espíritu de servicio', 'Espíritu de servicio'), ('Seguridad personal', 'Seguridad personal'), ('Asertividad', 'Asertividad'), ('Respeto a las opiniones', 'Respeto a las opiniones')], default='ninguna', max_length=50),
        ),
    ]
