# Generated by Django 2.1.4 on 2018-12-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181213_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_hunter',
            field=models.BooleanField(default='False'),
        ),
    ]
