# Generated by Django 2.1.4 on 2018-12-13 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_is_hunter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='academic_level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_hunter',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skillone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skillthree',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skilltwo',
        ),
    ]
