# Generated by Django 2.1.4 on 2018-12-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profileprey'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilehunter',
            name='is_hunter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profileprey',
            name='is_hunter',
            field=models.BooleanField(default=True),
        ),
    ]
