# Generated by Django 2.1.4 on 2018-12-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20181214_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileprey',
            name='is_hunter',
            field=models.BooleanField(default=False),
        ),
    ]
