# Generated by Django 2.1.4 on 2018-12-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='skill',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
